travis:
  secure:
    BINSTAR_TOKEN: aTF3nbFgYsg76/FtnoTTki678OAZnVONb6+9PQmYrGdxnq6QLugKtwZfzmhbmXxNy8wXahuJSv6D4BiwL8aRFapnqCgr4qkQO8mnFItLOx0q7IyJhR6an25t+F6H2QsytqlwuNfx0i/bYxCDtscvKYYNtHCNJuyTEmzwuKPvFAeVPFM3luhZ4IKT3lFwuiTfdn1/BryDtOsHiyalGiWgEV2JDRJ8GrTQMsecRC42BcxG9E5gC6Hx1K2hm3JUfhoNvZFb1ATImx9UtJFAZ8SOMvF02AjNfgouitOIzJm8ovKQjxCZBqbdS7XTwnjGnKKjczeDAkoiO/5k7ebZSgc6J1s/vmyN7AZ4ISC+CWnedAivJli2+yBUwvQo+i+JELYB2IW4OfDuAiZV06Etl3XatxMZve5RqEZl0pe9E62pNWZRndOEQp2pfZ4H42merJF+CJw4L4iSMcscijItTkyf4OxOt/30C52OP6WT8v9q3mdvsskAR94CgBb3dG330tPZy36jGeI2Gh9k/JOC8QvL0Jni733CJMGRXIgUkkSmXTLAoBG9l+d+GB39QjVFe7NtREztaSD/ZWBLW+gALtZozfPhmgZXbBSE18Y7Rm6kSJUol+YDp8qayLHq+2brQeTArxdiiznYRIjeIV9EGjt6syzYuxPGFCvJ2w8AxkU6Ofg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
